In [11]:
import sys
print(sys.version)
import pandas as pd
import math
import numpy as np
import matplotlib.pyplot as plt
import datetime
import bson
import gzip
import pickle
from collections import Counter
%matplotlib inline

2.7.11 |Anaconda 2.0.1 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]


In [1]:
import sys
print(sys.version)
from gensim import corpora, models
import pyLDAvis.gensim

2.7.11 |Anaconda 2.0.1 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]


In [2]:
corpus = corpora.MmCorpus('alexip_followers_py27.mm')
dictionary = corpora.Dictionary.load('alexip_followers_py27.dict')

In [3]:
lda = models.LdaModel.load('alexip.lda')
followers_data =  pyLDAvis.gensim.prepare(lda, corpus, dictionary)
pyLDAvis.display(followers_data)

/home/dkorolev/anaconda/lib/python2.7/site-packages/skbio/stats/ordination/_principal_coordinate_analysis.py:102: RuntimeWarning: The result contains negative eigenvalues. Please compare their magnitude with the magnitude of some of the largest positive eigenvalues. If the negative ones are smaller, it's probably safe to ignore them, but if they are large in magnitude, the results won't be useful. See the Notes section for more details. The smallest eigenvalue is -0.00318578017319 and the largest is 0.362549207622.
  RuntimeWarning


In [179]:
#followers_data

In [177]:
pyLDAvis.save_html(followers_data, 'followers_1000.html')

In [6]:
import gensim
#lda_vw = models.LdaModel.load('alexip_vw.lda')
lda_vw = gensim.models.wrappers.LdaVowpalWabbit.load('alexip_vw.lda')
followers_data_vw =  pyLDAvis.gensim.prepare(lda_vw, corpus, dictionary)
pyLDAvis.display(followers_data)

AttributeError: 'LdaVowpalWabbit' object has no attribute 'inference'

In [85]:
topic_term_dists.shape

(40, 25006)

In [127]:
np.sum(doc_topic_dists, axis=1)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [62]:
term_frequency = [0]*len(dictionary.dfs)
for k, v in dictionary.dfs.items():
    term_frequency[k] = v

In [63]:
doc_lengths = []
for doc in corpus:
    doc_lengths.append(sum([x[1] for x in doc]))

In [135]:
num_topics = 40
topic_term_dists = np.zeros((num_topics, len(term_frequency)))
with open('topics_all.dat', 'r') as f:
    counter = 0
    for line in f:
        counter += 1
        if counter > 10:
            prob = [float(x) for x in line.split(' ')[1:-1]]
            for i in range(num_topics):
                topic_term_dists[i,(counter-11)%len(term_frequency)] += prob[i]
            #topic_term_dists.append(np.array())
#topic_term_dists = np.array(topic_term_dists)
#topic_term_dists = topic_term_dists[:len(term_frequency),:]

In [144]:
topic_term_dists.T/np.sum(topic_term_dists.T, axis=0)
#topic_term_dists = topic_term_dists.T
#topic_term_dists = topic_term_dists/np.sum(topic_term_dists, axis=0)
#topic_term_dists = topic_term_dists.T

array([[  4.19616039e-05,   5.28813477e-05,   4.19616039e-05, ...,
          4.19616039e-05,   4.19616039e-05,   4.19616039e-05],
       [  4.19610698e-05,   2.75388699e-05,   4.19610698e-05, ...,
          4.19610698e-05,   4.19610698e-05,   4.19610698e-05],
       [  4.19616420e-05,   1.63439209e-04,   4.19616420e-05, ...,
          4.19616420e-05,   4.19616420e-05,   4.19616420e-05],
       ..., 
       [  3.81486430e-05,   3.63297100e-06,   3.81486430e-05, ...,
          3.81486430e-05,   3.81486430e-05,   3.81486430e-05],
       [  3.81470790e-05,   2.53038465e-06,   3.81470790e-05, ...,
          3.81470790e-05,   3.81470790e-05,   3.81470790e-05],
       [  3.81464687e-05,   1.51696870e-06,   3.81464687e-05, ...,
          3.81464687e-05,   3.81464687e-05,   3.81464687e-05]])

In [148]:
doc_topic_dists = np.zeros((len(doc_lengths), num_topics))
with open('prediction_all.dat', 'r') as f:
    counter = 0
    for line in f:
        prob=[float(x) for x in line.split(' ')[:-1]]
        for i in range(num_topics):
            doc_topic_dists[counter%len(doc_lengths),i] += prob[i]
        counter += 1
        #doc_topic_dists.append(np.array([float(x) for x in line.split(' ')[:-1]]))
#doc_topic_dists = np.array(doc_topic_dists)
#doc_topic_dists = doc_topic_dists[:len(doc_lengths),:].T
#doc_topic_dists = doc_topic_dists.T
#doc_topic_dists = doc_topic_dists/np.sum(doc_topic_dists, axis=0)
#doc_topic_dists = doc_topic_dists.T

In [155]:
(doc_topic_dists/np.sum(doc_topic_dists, axis=0)).shape

(542, 40)

In [156]:
np.sum(doc_topic_dists, axis=0).shape

(40,)

In [172]:
np.sum((doc_topic_dists.T/np.sum(doc_topic_dists.T, axis=0)).T, axis=1)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1

In [24]:
vocab = ['']*len(dictionary.token2id)
for k, v in dictionary.token2id.items():
    vocab[v] = k

In [173]:
data = {'topic_term_dists': (topic_term_dists.T/np.sum(topic_term_dists.T, axis=0)).T, 
            'doc_topic_dists': (doc_topic_dists.T/np.sum(doc_topic_dists.T, axis=0)).T,
            'doc_lengths': doc_lengths,
            'vocab': vocab,
            'term_frequency': term_frequency}

In [174]:
print('Topic-Term shape: %s' % str(np.array(data['topic_term_dists']).shape))
print('Doc-Topic shape: %s' % str(np.array(data['doc_topic_dists']).shape))

Topic-Term shape: (40, 25006)
Doc-Topic shape: (542, 40)


In [175]:
vis_data = pyLDAvis.prepare(**data)

/home/dkorolev/anaconda/lib/python2.7/site-packages/joblib-0.9.4-py2.7.egg/joblib/hashing.py:197: DeprecationWarning: Changing the shape of non-C contiguous array by
descriptor assignment is deprecated. To maintain
the Fortran contiguity of a multidimensional Fortran
array, use 'a.T.view(...).T' instead
  obj_bytes_view = obj.view(self.np.uint8)
/home/dkorolev/anaconda/lib/python2.7/site-packages/joblib-0.9.4-py2.7.egg/joblib/hashing.py:197: DeprecationWarning: Changing the shape of non-C contiguous array by
descriptor assignment is deprecated. To maintain
the Fortran contiguity of a multidimensional Fortran
array, use 'a.T.view(...).T' instead
  obj_bytes_view = obj.view(self.np.uint8)
/home/dkorolev/anaconda/lib/python2.7/site-packages/joblib-0.9.4-py2.7.egg/joblib/hashing.py:197: DeprecationWarning: Changing the shape of non-C contiguous array by
descriptor assignment is deprecated. To maintain
the Fortran contiguity of a multidimensional Fortran
array, use 'a.T.view(...).T' instead

In [176]:
pyLDAvis.display(vis_data)

In [181]:
target_path = 'all'

In [183]:
corpus_all = corpora.MmCorpus(target_path + '/corpora_corpus.mm')
dictionary_all = corpora.Dictionary.load(target_path + '/corpora.dict')

In [184]:
lda_all = models.LdaModel.load(target_path + '/corpora.lda')
followers_data_all =  pyLDAvis.gensim.prepare(lda_all, corpus_all, dictionary_all)
pyLDAvis.display(followers_data_all)

In [35]:
len(doc_lengths)

542